### PR TITLE
UI Merge

### LINKED ISSUE #11: Main menu
Project should have main menu to allow user to choose operation mode

### PR DESCRIPTION
**Pull request by BartoszRodak**
Created base window - view model
Created basic main menu
Established base interface for future views

### CODE REVIEW

**Comment by ErykKrupa** [comment]
Do rebase with master locally to be up-to-date and push it again without making new pull request.

**Comment by ErykKrupa** [comment]
On current stage of project we able to add more functionality on this branch (e.g. blank windows for play and train, working exit button) before merging to master.

**Review by KamilKrol5 — APPROVED** [review]

**Review by ErykKrupa — CHANGES_REQUESTED** [review]
Do rebase with master locally to be up-to-date and push it again without making new pull request.
On current stage of project we are able to add more functionality on this branch (e.g. blank windows for play and train, working exit button) before merging to master.

**Comment by ErykKrupa** [comment]
This pull request is linked with UI issue, but these changes don't solve the case. I suggested before to split UI issue into smaller parts, that could be linked and merged individually.

**Review by ErykKrupa — APPROVED** [review]

**Pull request merged**
